---
title: "LinearMixedModelPropensity"
author: "Christina De Cesaris"
date: "3/10/2021"
output: html_document
---

```{r}
library(lmerTest)
library(MASS)
library(AER)
library(scales)
library(redres)
library(MatchIt)
library(stargazer)
#install.packages("stargazer")
data(Guns)
```

```{r transformation}
#distribution of response
par(mfrow=c(1,2))
hist(Guns$violent) #TODO, ADD AXIS
hist(log(Guns$violent))
```



```{r levels plot}
#quick inverse weight propensity scores for law
sapply(Guns, class)

cor(Filter(is.numeric,Guns))

pairs(Filter(is.numeric,Guns)) #correlations


boxplot(Guns$violent~Guns$law) #TODO, add axis, legend, titles etc
```

```{r Unweighted LMM}
#before weights
mod_pre = lmer(log(violent)~law+male+robbery+murder+prisoners+density+(1|state)+(1|year), data=Guns) 
summary(mod_pre)
```

```{r prebalance, results='asis' }
library(knitr)
#wip balance analysis
#bal1= glm(violent~l, Guns)
#summary(bal1)


bal1= lm(male~law, Guns)
kpre1=kable(summary(bal1)[4],
            caption = "lm(male ~ law)")



bal2= lm(robbery~law, Guns)
kpre2=kable(summary(bal2)[4],
            caption = "lm(robbery ~ law)")


bal3= lm(murder~law, Guns)
kpre3=kable(summary(bal3)[4],
            caption = "lm(murder ~ law)")


bal4= lm(density~law, Guns)
kpre4=kable(summary(bal4)[4],
            caption = "lm(density ~ law)")

bal_pre = list(kpre1,kpre2, kpre3, kpre4)
bal_pre
```

```{r pscores}

#obtain weights using logistic regression and inverse weighted propensity scores
mod_log = glm(law~male+robbery+murder+prisoners+density,family=binomial, Guns)
summary(mod_log)

prob= mod_log$fitted

pscore = ifelse(Guns$law=='yes', prob, 1-prob)
Guns$pscore=pscore
weight=1/pscore
hist(pscore) #distribution right skewed, not terrible extremes, consider trimming [0.01,0.99]
summary(pscore)
Guns$pscore=pscore
Guns$pscore=ifelse(pscore>0.99, 0.99, Guns$pscore)
Guns$pscore=ifelse(pscore<0.01, 0.01, Guns$pscore)
summary(Guns$pscore)


col.alpha<-function(color, alpha){
  code=col2rgb(color)/256
  rgb(code[1],code[2],code[3],alpha)
}

#better  hist
hist(Guns$pscore[Guns$law=='yes'], breaks=25, col=col.alpha("red",.6), freq=F, ylim=c(0,5), xlab="Propensity Score", ylab="", main="Propensity Score Distribution")
hist((Guns$pscore[Guns$law=='no']), breaks=25, col=col.alpha("lightblue",.6), freq=F, ylim=c(0,5), xlab="Propensity Score", ylab="", main="",add=T)
legend(.4, 5, legend=c("Law: Yes", "Law: No"),
       col=c("red", "blue"),fill = c("red", "lightblue") )
```


```{r postbalance,results='asis' }



bal1= lm(male~law, Guns, weights=weight)
kpost1=kable(summary(bal1)[5],
            caption = "lm(male ~ law)")



bal2= lm(robbery~law, Guns, weights=weight)
kpost2=kable(summary(bal2)[5],
            caption = "lm(robbery ~ law)")


bal3= lm(murder~law, Guns, weights=weight)
kpost3=kable(summary(bal3)[5],
            caption = "lm(murder ~ law)")


bal4= lm(density~law, Guns, weights=weight)
kpost4=kable(summary(bal4)[5],
            caption = "lm(density ~ law)")

bal_post = list(kpost1,kpost2, kpost3, kpost4)
bal_post
```

```{r weighted LMM}
mod_post = lmer(log(violent)~law+male+robbery+murder+prisoners+density+(1|state)+(1|year), data=Guns, weights=weight)

summary(mod_post)


```


```{r Diagnostics}
plot_redres(mod_post, type = "std_cond")
plot_resqq(mod_post)
plot_ranef(mod_post)
```





